### ISSUE TITLE
Views folder needs __init__.py

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [ryneeverett/cartridge-downloads#7]
Hey, thanks for your work here, this is exactly what I need! There were some issues with view importing until I added an ``__init__.py`` into the views folder, just a heads up. Looking forward to using this. I'd be glad to help contribute once the project I'm launching cartridge-downloads with gets deployed.

**Comment by geoffrey-eisenbarth** [comment]
Looks like the same thing is needed for the template tags folder, FYI.

**Comment by ryneeverett** [comment]
Are you using python2? My understanding is that `__init__.py` files are only needed in python2 packages.

I've only used and run the test suite against python3 and would be surprised if that was the only python2 issue. I'd be happy to support python2 if someone did the legwork to get it working though.

Thanks for the feedback and running a second set of eyes over the code.

**Comment by geoffrey-eisenbarth** [comment]
Oh, I wasn't familiar with that difference between 2 and 3. I'm running 2.7 at the moment, and so far these issues have been the only ones I've seen. I'll probably end up going through the code line by line as I continue to implement it on my site so I'll keep my eyes out for any similar issues. Imho since Mezzanine and Cartridge support python2 and contain ``__init__.py``s I think this project should as well, but it's  your call!

**Comment by ryneeverett** [comment]
I'm fine with adding python2 support but I'm also fine with not adding it if nobody needs it.

Since it sounds like you're new to the python ecosystem, let me strongly suggest using python3 if you can. It isn't that much better than python2, but python2 will not be maintained beyond 2020. https://pythonclock.org/

**Comment by geoffrey-eisenbarth** [comment]
Understandable! I didn't realize 2.7 was being depreciated in 2020, I might
as well make the switch soon. I need to get this site deployed in the
coming week, so I'll probably hold off on switching and updating my code
until after that, but thanks for the advice!

**Comment by ryneeverett** [comment]
Just pushed added the `__init__.py` files and test support for python2. That's no guarantee there aren't more python2 incompatibilities that the test suite missed though.
