### ISSUE TITLE
Readme typo

### ISSUE THREAD

**Issue by geoffrey-eisenbarth** [ryneeverett/cartridge-downloads#8]
README.md says to add a ``SHOP_OPTION_TYPE_CHOICE`` called 'Download' in order to get download only type functionality, but utils.py looks for a type choice called 'Downloads'. Perhaps allow both to catch potential typos, or fix in the Readme.

I don't mind making a branch, implementing these, and making a pull request once I get my shop running.

**Comment by ryneeverett** [comment]
Thanks for the report. Sticking with just the plural seems simplest to me.

**Comment by ryneeverett** [comment]
If we did want to enable alternative names for this, I would think adding a configuration option like `CARTRIDGE_DOWNLOADS_OPTION_TYPE_NAME` would be more flexible than checking for every conceivable name.
